const en = {
  '20MDollarInMonth': 'ماهانه تا 2M$',
  '24H_CHANGE': 'تغییرات 24ساعته',
  '24H_HIGH': 'حداکثر 24ساعته',
  '24H_LOW': 'حداقل 24ساعته',
  '24H_VOLUME': 'حجم 24ساعته',
  '50KDollarInDay': 'روزانه تا 50K$',
  '100BTCInDay': 'روزانه تا 100 BTC',
  '200KDollarInDay': 'روزانه تا 200K$',
  '500KDollarInMonth': 'ماهانه تا 500K$',
  ABOUT_US: 'درباره ما',
  ADDRESS: 'آدرس',
  ACCOUNTACTIVITY: 'فعالیت حساب',
  ACCOUNT_TYPE: 'نوع حساب',
  ACTIONS: 'عملیات',
  ACTIVATION: 'فعالسازی',
  ACTIVE: 'فعال',
  ACTIVE_USER: 'فعالیت اخیر',
  ACTIVITIES: 'فعالیت‌ها',
  ALL: 'کل',
  fa: 'فارسی',
  yesterday: 'دیروز',
};

// export default fa;
