const en = {
  '100BTCInDay': 'Daily up to 100 BTC',
  '200KDollarInDay': 'Daily up to $ 200K',
  '20MDollarInMonth': 'Monthly up to $ 2m',
  '24H_CHANGE': '24 hour changes',
  '24H_HIGH': 'A maximum of 24 hours',
  '24H_LOW': 'At least 24 hours',
  '24H_VOLUME': '24 hour volume',
  '500KDollarInMonth': 'Monthly up to $ 500K',
  '50KDollarInDay': 'Daily to $ 50K',
  ABOUT_US: 'about us',
  ACCOUNTACTIVITY: 'Account activity',
  ACCOUNT_TYPE: 'Account type',
  ACTIONS: 'the operation',
  ACTIVATION: 'Activation',
  ACTIVE: 'active',
  ACTIVE_USER: 'Recent activity',
  ACTIVITIES: 'activities',
  ADDRESS: 'Address',
  ALL: 'Total',
  AMOUNT: 'Amount',
  APIMANAGEMENT: 'Manage APIs',
  API_KEY: 'Key API.',
  API_LIMITATIONS: 'Limit the API.',
  API_MANAGEMENT: 'Manage APIs',
  ASSET: 'Property',
  AVAILABLE: 'Available',
  BALANCE_DETAILS: 'Account Information',
  BITCOIN: 'Bitcoin',
  BUY: 'Buy',
  CHANGEPASSWORD: 'change Password',
  CLASSIC: 'Classic',
  COIN: 'cryptocurrency',
  CONFIRM: 'Confirmed',
  CONFIRMEMAIL: 'Post confirmation',
  CONFIRMEMAIL_EXPLANATION:
    'Enter your email for full access to site facilities.',
  CONFIRMPHONENUMBER: 'Confirm call number',
  CONFIRMPHONENUMBER_EXPLANATION:
    'Enter your contact number for full access to site facilities.',
  CONTACT_US: 'Contact us',
  CONVERT: 'Convert',
  DAILYNEWS: 'Daily news',
  DASHBOARD: 'Dashboard',
  DEACTIVATING_ACCOUNT: 'Deactivate Account',
  DEACTIVEACCOUNT: ' Deactivate Account',
  DELETE: 'Delete',
  DEPOSIT: 'deposit',
  DEPOSITANDWITHDRAW_HISTORY: 'History of deposit and harvest',
  DEVICEMANAGEMENT: 'Manage devices',
  DEVICEMANAGEMENT_EXPLANATION:
    'Manage devices that you have access to your account.',
  DEVICES: 'Devices',
  DISTRIBUTION: 'Play',
  DOLLAR: 'Dollar',
  DONOTSHOW: 'Failing to show',
  EDIT: 'Edit',
  EDIT_LIMITATIONS: 'Edit limitations',
  ESTIMATEDVALUE: 'Approximate value',
  ESTIMATED_VALUE: 'Approximate value',
  FAVORITES: 'Indicated',
  FIAT: 'Fiat',
  FIATANDSPOT: 'Fiat and Spot.',
  FIAT_BALANCE: "Fiat's credit",
  FINISHED: 'done',
  FRIENDS: 'Friends',
  FRIENDS_USER_ID: 'User Code',
  IDENTIFICATION: 'Authentication',
  IMPORTANTACTIONS: 'Important measures',
  INACTIVE: 'Inactive',
  INCREASE_YOUR_SECURITY: 'Increase your account security',
  INORDER: 'In order',
  INPROGRESS: 'doing',
  INSTALL: 'Installation',
  IP_LIMITATIONS: 'IP restriction',
  LASTLOGIN: 'Last Login:',
  LASTPRICE: 'last price',
  LAST_DEPOSIT: 'Recent deposits',
  LOGINANDACTIONHISTORY: 'History of entry and activity',
  LOGOUT: 'Exit the account',
  MAKING: 'You make',
  MARGIN: 'Margin',
  MARKET: 'Market',
  MARKETCAP: 'Market roof',
  MARKETLISTWIDGET_TABLESUBTITLE: 'More than 100 currency passwords',
  MARKETLISTWIDGET_TABLETITLE: 'List of currencies',
  MENU_DASHBOARD: 'Dashboard',
  NETWORK: 'Network',
  NOTE: 'Notes',
  NOTHING_FOUND: 'Nothing found.',
  NOTIFICATIONS: 'Announcements',
  OPENORDERS: 'Open orders',
  ORDERS: 'orders',
  OVERALL_BALANCE: 'General credit',
  OVERVIEW: 'Overview',
  PAIR: 'symbols',
  PAYMENT: 'Payment and accounting',
  PREFERENCES: 'General',
  PRIZES: 'Awards and gifts',
  RECEIVED_COMMISSION: 'Received the fee',
  REFERRAL: 'introduce to friends',
  REFERRAL_ID: 'Invitation Code',
  REGISTRATION_TIME: 'Registration time',
  REWARD_CENTER: 'Awards and gifts',
  RULES: 'Terms and Conditions',
  SCAT_TO_GET_THE_ADDRESS: 'Scan to get the address.',
  SEARCH: 'Search',
  SECRET_KEY: 'The secret code',
  SECURITY: 'Security account',
  SELECT_COIN: 'Choose a currency code',
  SETTINGS: 'Settings',
  SHOW: 'the show',
  SPOT: 'Spot.',
  SPOTMARKETS: 'Spot Markets',
  SPOT_BALANCE: 'Spot credentials',
  STATUS: 'Condition',
  STRUCTURE: 'Structure',
  SUSPICIOUSACTIVITY: 'Did you see suspicious activity?',
  TAKING: 'take',
  TASK_CENTER: 'Important measures',
  TIME: 'Time',
  TRADE: 'Tried',
  TRADINGFEELEVEL: 'The level of your transactions',
  TRANSACTIONHISTORY: 'History of transactions',
  TRANSFER: 'the transfer',
  TRANSFER_TO: 'Transfer to',
  TWOFACTORAUTHENTICATION: 'Two-factor authentication',
  TWOFACTORAUTHENTICATOR: 'Two-factor identification code',
  TWOFACTORAUTHENTICATOR_EXPLANATION: 'Protect your account and transactions.',
  TWO_FACTOR_PASSWORD: 'Two-factor password',
  TYPE: 'Type',
  UNSUCCESSFULDEPOSIT: 'Your deposit has not been done? click.',
  UNSUCCESSFULWITHDRAW: 'Your withdrawal has not been done? click.',
  VALUE: 'Value',
  VISIT: 'View',
  WALLETOVERVIEW: 'Overview',
  WALLETS: 'Kiev',
  WITHDRAW: 'harvest',
  WITHDRAW_CAP: 'Picked up the roof',
  YOU_RECEIVE_FRIENDS_RECEIVE: 'You take / friends take you',
  abilityToWatchMarket: 'Ability to view the market',
  accessLimitationForDesiredIPs: 'Access restrictions for desired IPs',
  action: 'the operation',
  activities: 'activities',
  address: 'Address',
  afterLevel2Confirm: 'After approval of level 2',
  air: 'Air',
  allMessages: 'All messages',
  amount: 'Volume',
  antifishCode: 'Anti-honey code',
  arrivalTimeSpace: 'arriving time:',
  average: 'Average',
  beyondSixMonths: 'Before the last 6 months',
  buildApi: 'Build API.',
  buildYourAccount: 'Make your account',
  buyAndSellCrypto: 'Buy and sell currency!',
  buyCryptoHistory: 'History of the purchase of Retaz',
  cancel: 'Cancellation',
  cancelAllOrders: 'Cancel all orders',
  clearAll: 'Erase all',
  confirmAddressAndPhoneNumber: 'Confirm address and phone number',
  confirmBankAccount: 'Confirm bank account',
  confirmIdCardAndIdentification: 'National card approval and authentication',
  confirmationOfLevel1: 'Confirm the initial level',
  confirmationOfLevel2: 'Average level confirmation',
  confirmed: 'Accepted',
  convert: 'Convert',
  convertHistory: 'History of the Transformation of the Retizers',
  customDateSelection: 'Manual selection of history',
  date: 'Date',
  deleteAllApis: ' Remove all APIs',
  depositTo: 'Deposit to',
  didntReceiveTheCode: 'Did not receive the code?',
  doIdentification: 'Authenticate',
  doItNow: 'Action right now.',
  done: 'done',
  emailVerificationExplanation1: 'Please send 6 digit code to mobile number',
  emailVerificationExplanation2: ' enter. This code is up to 30 minutes.',
  ensureNetworksMatchesTheAdrressesNetwork:
    'Make sure to match the network address with the entered network address to prevent the loss of the amount.',
  executed: 'Executed',
  export: 'Received',
  exportBuyCryptoHistory: 'Get the history of buying Ramel',
  exportOrderHistory: 'Get the history of orders',
  exportTradeHistory: 'Get the history of transactions',
  fastAndEasy: 'Fast and easy',
  fee: 'Wage',
  feeRules: 'The rules of the fee',
  feeSpace: 'Wage:',
  fees: 'The goods',
  filled: 'full',
  filter: 'Filter',
  finalAmount: 'the final Volume',
  from: 'From',
  generateTaxStatementsApi: 'API Create Tax Report',
  hideAllCanceled: 'Failed to display cancels',
  hideReadNotifications: 'Failed to view',
  hitobitNews: 'Heath and bit news',
  keepYourApisSafe:
    'Do not share your API key with someone to keep your assets safe.',
  last24Hours: 'Last 24 hours',
  lastDay: 'yesterday',
  lastMonth: 'Previous month',
  lastSixMonths: '6 months of recent',
  lastThreeMonths: 'The last three months',
  lastTwoWeeks: 'Recent two weeks',
  lastWeek: 'Last week',
  level1: 'Initial level',
  level2: 'average level',
  level3: 'Advanced level',
  listOfAddresses: 'List of addresses',
  listOfApis: 'List of APIs',
  lowSecurity: 'Low security',
  maximum30Apis: 'Each user can create up to 30 APIs.',
  method: 'Method',
  monthToDate: 'The last month',
  mostPopular: 'The most popular',
  nameYourApiToContinue: 'Naming your API to continue.',
  network: 'Network',
  'network:': 'Network:',
  newMessages: 'New message',
  noLimitation: 'unlimited',
  notAbleToDepositWithdrawAndTrade:
    'Impossibility of deposit, harvesting and transaction',
  nothingFound: 'Nothing found.',
  notifSetting: 'Notification settings',
  notifications: 'Announcements',
  openOrders: 'Open orders',
  orderHistory: 'History of orders',
  pair: 'Currency pair',
  phoneNumberVerification: 'Verify mobile number',
  price: 'Price',
  readAll: 'Read all',
  readingPermission: 'Read permit',
  recentWithdraws: 'Recent impressions',
  resendEmail: 'Re-send email',
  resendSMS: 'Re-send code',
  reset: 'Reset',
  search: 'Search',
  selectCoin: 'Selection of Retaz',
  selectCoinForDeposit: 'Selection of Retaz for deposit',
  selectCoinForWithdraw: 'Selection of Retaz for harvest',
  selectCountryCode: 'Select country code',
  selectNetwork: 'Network selection',
  selectTimePeriod: 'Select the desired time interval.',
  selectedTimeCannotExceed3Month:
    'The selected time interval cannot be more than 3 months.',
  side: 'SIDE',
  spotOrders: 'Spotting orders',
  status: 'Condition',
  systemMessages: 'System messages',
  to: 'until the',
  total: 'Total',
  tradeHistory: 'History of transactions',
  tradeNotifications: 'Treated Notifications',
  tradingPermission: 'The transaction authorization',
  triggerConditions: 'Terms of activation',
  type: 'Type',
  upTo10000DataCanBeGeneratedEachTime:
    'At each turn up to 1000 data can be obtained.',
  userPersonalData: 'User personal information',
  viewAll: 'See all',
  withdrawPermission: 'Permit',
  withinSixMonths: 'In the last 6 months',
  yesterday: 'Yesterday',
};

module.exports = en;
